apiVersion: apps/v1
kind: Deployment
metadata:
  name: vtmp3
  labels:
    app: vtmp3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vtmp3
  strategy:
     type: RollingUpdate
     rollingUpdate:
       maxSurge: 3
  template:
    metadata:
      labels:
        app: vtmp3
    spec:
      containers:
        - name: vtmp3
          image: inveigle/system-design
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: configmap
            - secretRef:
                name: secret